### ISSUE TITLE
[req] Automate zoom levels

### ISSUE THREAD

**Issue by Powback** [Hattiwatti/BF3MinimapGenerator#1]
Run x times to generate multiple zoom levels.
Level 0 -2048 
Level 1 - 1024
Level 2 - 512
Level 3 - 256

Resulting images can be put straight into leaflet js.

**Comment by Hattiwatti** [comment]
I take it that by those numbers you mean meters*meters and not picture size?

**Comment by Powback** [comment]
Yes, that would be correct. The generated files should have the same resolution on all levels.

The way it has been accomplished until now is to manually set the OrthoView to 2048, divide it by two and then run it again. The result is exactly what I'm looking for, although automatically. 

Level 0 should produce 1 file
Level 1 should produce 4 files
Level 2 should produce 16 files
Level 3 should produce 64 files.

It would also be nice if the files could be placed in their appropriate folder based on zoom.
